//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int Id { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> PayrollPeriod { get; set; }
        public Nullable<int> OTHours { get; set; }
        public Nullable<decimal> OTPay { get; set; }
        public Nullable<decimal> HolidayPay { get; set; }
        public Nullable<decimal> LeavePay { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> SSS { get; set; }
        public Nullable<decimal> PHIC { get; set; }
        public Nullable<decimal> PagIbig { get; set; }
        public Nullable<decimal> Tardiness { get; set; }
        public Nullable<decimal> CashAdvance { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
    }
}
