//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollModule.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<PayrollPeriod> PayrollPeriods { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SalaryCompensation> SalaryCompensations { get; set; }
    
        public virtual ObjectResult<GetSalaryAndCompensationWithEmployeeFullname_Result> GetSalaryAndCompensationWithEmployeeFullname()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalaryAndCompensationWithEmployeeFullname_Result>("GetSalaryAndCompensationWithEmployeeFullname");
        }
    
        public virtual ObjectResult<GetPayrollFromPayrollPeriod_Result> GetPayrollFromPayrollPeriod(Nullable<int> payrollPeriodID)
        {
            var payrollPeriodIDParameter = payrollPeriodID.HasValue ?
                new ObjectParameter("PayrollPeriodID", payrollPeriodID) :
                new ObjectParameter("PayrollPeriodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPayrollFromPayrollPeriod_Result>("GetPayrollFromPayrollPeriod", payrollPeriodIDParameter);
        }
    }
}
