//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryCompensation
    {
        public int Id { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> OvertimeRate { get; set; }
        public Nullable<decimal> SSS { get; set; }
        public Nullable<decimal> PHIC { get; set; }
        public Nullable<decimal> PagIbig { get; set; }
    }
}
